[package]
name = "paficent/tableutils"
description = "Asynchronous programming primitives"
version = "1.0.3"
license = "MIT"
authors = ["Paficent"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"


exclude = [".github", "rokit.toml", "moonwave.toml", "README.MD", "LICENSE", "defaultproject.json",]