[package]
name = "paficent/tableutils"
description = "Asynchronous programming primitives"
version = "1.0.2"
license = "MIT"
authors = ["Paficent"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"


exclude = ["lune", "aftman.toml", "moonwave.toml", "README.MD"]